version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: gym_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5433:5432"  # Maps host port 5433 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: